
title: Penetration Testing Notes
description: >- # this means to ignore newlines until "baseurl:"
  Documented notes and learning for penetration testing and related cyber security testing.
baseurl: "/pen-test-docs" # the subpath of your site, e.g. /blog
url: "https://alipali737.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: pdmosses/just-the-docs@combination-rec-nav

aux_links:
  "Github Source":
    - "//github.com/alipali737/pen-test-docs"
